config/routes.rb
Rails.application.routes.draw do

  # These routes handle the permalink controller, which is at go.humap.[dev|site], but actually on this application.
  #
  constraints subdomain: "go", domain: ENV['PERMALINK_DOMAIN'] do
    get "/",  to: redirect(subdomain: "admin", path: "/")
    get "/:id", to: "permalinks#redirect", as: :permalink
  end

  # backup, allow go.humap.site or go.humap.dev to hit the right place too
  get "/:id", to: "permalinks#redirect", constraints: { subdomain: "go"}

  resources :permalinks, only: [] do
    member do
      get :qr_code, defaults: {format: :svg}
    end
  end

  devise_for :super_admin_users, ActiveAdmin::Devise.config.merge(path: :super_admin)
  devise_for :tenant_users, ActiveAdmin::Devise.config.merge(
              controllers: {
                invitations: 'tenant_users/invitations',
                sessions: 'tenant_users/sessions',
                unlocks: 'tenant_users/unlocks',
                passwords: 'tenant_users/passwords',
                registrations: 'tenant_users/registrations'
              })
              
  devise_scope :tenant_user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  ActiveAdmin.routes(self)

  # This block iterates over config/frontend_routes.yml and creates named routes for the things in there.
  # The YAML uses the same interpolation patterns as I18n YAML files.
  Rails.configuration.frontend_routes.each do |resource, route|
    route_name = resource.to_s.camelize.demodulize.underscore
    direct route_name do |res|
      if res.class.to_s.underscore != resource.to_s
        raise ActionController::RoutingError, "You've passed a #{res.class} object into a #{route_name} route"
      elsif !res.respond_to?(:tenant) || !res.tenant.present?
        raise ActionController::RoutingError, "You've defined a route in frontend_routes.yml for #{res.class}, which doesn't respond to .tenant, or tenant isn't present"
      else
        interpolated_route = route.gsub(Regexp.union(I18n.config.interpolation_patterns)) do |match|
          if match == '%%'
            '%'
          else
            key = ($1 || $2 || match.tr("%{}", "")).to_sym
            value = if res.respond_to?(key)
                      res.send(key)
                    else
                      raise ActionController::RoutingError, "You've defined #{key} in the frontend routes, which the #{res.class} class doesn't respond to"
                    end
            $3 ? sprintf("%#{$3}", value) : value
          end
        end
        "https://#{res.tenant.custom_domain}/#{interpolated_route}"
      end
    end
  end


  
  root to: "admin/pages#index"

  resources :webhooks, only: [] do
    collection do
      post 'rebuild'
      post 'netlify_build_status', defaults: {format: :json}

    end
  end

  resources :tenants, only: [] do
    member do
      get 'stylesheet', defaults: {format: :scss}
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/pages/_form.html.erb
<%= semantic_form_for [:admin, @page], builder: ActiveAdmin::FormBuilder, url: @page.persisted? ? admin_page_path : admin_pages_path do |f| %>
    <%= f.semantic_errors %>
    <div class="tabs">
        <ul class="nav nav-tabs" role="tablist">
            <li><a href="#details">Page Details</a></li>
            <li><a href="#content">Content</a></li>
            <li><a href="#images">Images</a></li>
            <li><a href="#ctas">Calls to Action</a></li>
            <li><a href="#quickstarts">Quickstarts</a></li>
        </ul>
        <div class="tab-content">
            <%= f.inputs do %>
                <div id="details">
                    <h3 class="m-fieldset-subheader">Page Details</h3>
                    <%= f.input :name, label: "Title" %>
                    <%= f.input :active_admin_state_event,
                                label: 'Status',
                                as: :select,
                                collection: f.object.aasm.permitted_transitions.map { |pt| [pt[:state], pt[:event]] },
                                include_blank: false,
                                selected: f.object.aasm.permitted_transitions.find { |pt| pt[:state] == f.object.state.to_sym }[:event] %>
                    <%= f.input :page_type, label: "Page Type", include_blank: false, input_html: {data: {not: 'home_page', action: 'hide', target: '.search-image,.carousel-images', else: 'hide .single-image'}} %>
                    <%= f.input :description, label: "Description", input_html: {rows: 5} %>
                    <%= f.input :page_location, include_blank: true, collection: Humap::Pages::Page::LOCATIONS %>
                </div>
                
                <div id="content">
                    <h3 class="m-fieldset-subheader">Page Content</h3>
                    <div class="m-wysiwyg-container<%= " error" if f.object.errors[:content].any? %>">
                        <%= f.rich_text_area :content %>
                        <% if f.object.errors[:content].any? %>
                            <p class="inline-errors"><%= f.object.errors[:content].first %></p>
                        <% end %>
                    </div>   
                </div>

                <div id="images">
                    <div class="single-image">
                        <h3 class="m-fieldset-subheader">Page Image</h3>
                        <%= f.fields_for :image do |page_image| %>
                            <%= page_image.input :file, as: :file, hint: page_image.object.file.attached? ? ix_image_tag(page_image.object.file.key, url_params: {w: 100, h: 100}) : "" %>
                            <%= page_image.input :name %>
                        <% end %>
                    </div>


                    <div class="carousel-images">
                        <h3 class="m-fieldset-subheader">Carousel Images</h3>
                        <% f.has_many :images, heading: false, allow_destroy: true do |img| %>
                            <% img.input :file, as: :file, hint: img.object.file.attached? ? ix_image_tag(img.object.file.key, url_params: {w: 100, h: 100}) : "" %>
                            <% img.input :name %>
                        <% end %>
                    </div>

                    <div class="search-image">
                        <h3 class="m-fieldset-subheader">Search Image</h3>
                        <%= f.fields_for :search_image do |search_image| %>
                            <%= search_image.input :file, as: :file, hint: search_image.object.file.attached? ? ix_image_tag(search_image.object.file.key, url_params: {w: 100, h: 100}) : "" %>
                            <%= search_image.input :name %>
                        <% end %>
                    </div>


                </div>


                <div id="ctas">
                    <h3 class="m-fieldset-subheader">Calls to Action</h3>
                    <% f.has_many :cta_blocks, heading: false, allow_destroy: true do |cta| %>
                        <% cta.input :title %>
                        <% cta.input :content %>
                        <% cta.input :url %>
                        <% cta.input :button_text %>
                    <% end %>

                </div>

                <div id="quickstarts">
                    <div class="quickstarts">
                        <h3 class="m-fieldset-subheader">Highlighted Quick Starts</h3>
                        <% f.input :highlighted_content_intro, label: "Introduction", input_html: {rows: 5} %>
                        <% f.input :quick_starts, as: :searchable_select, label: "Quick Starts" %>
                    </div>
                </div>
                
            <% end %>
        </div>
        <%= f.actions %>
    </div>


<% end %>