config/routes.rb
Rails.application.routes.draw do

  # These routes handle the permalink controller, which is at go.humap.[dev|site], but actually on this application.
  #
  constraints subdomain: "go", domain: ENV['PERMALINK_DOMAIN'] do
    get "/",  to: redirect(subdomain: "admin", path: "/")
    get "/:id", to: "permalinks#redirect", as: :permalink
  end

  # backup, allow go.humap.site or go.humap.dev to hit the right place too
  get "/:id", to: "permalinks#redirect", constraints: { subdomain: "go"}

  resources :permalinks, only: [] do
    member do
      get :qr_code, defaults: {format: :svg}
    end
  end

  devise_for :super_admin_users, ActiveAdmin::Devise.config.merge(path: :super_admin)
  devise_for :tenant_users, ActiveAdmin::Devise.config.merge(
              controllers: {
                invitations: 'tenant_users/invitations',
                sessions: 'tenant_users/sessions',
                unlocks: 'tenant_users/unlocks',
                passwords: 'tenant_users/passwords',
                registrations: 'tenant_users/registrations'
              })
              
  devise_scope :tenant_user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  ActiveAdmin.routes(self)

  # This block iterates over config/frontend_routes.yml and creates named routes for the things in there.
  # The YAML uses the same interpolation patterns as I18n YAML files.
  Rails.configuration.frontend_routes.each do |resource, route|
    route_name = resource.to_s.camelize.demodulize.underscore
    direct route_name do |res|
      if res.class.to_s.underscore != resource.to_s
        raise ActionController::RoutingError, "You've passed a #{res.class} object into a #{route_name} route"
      elsif !res.respond_to?(:tenant) || !res.tenant.present?
        raise ActionController::RoutingError, "You've defined a route in frontend_routes.yml for #{res.class}, which doesn't respond to .tenant, or tenant isn't present"
      else
        interpolated_route = route.gsub(Regexp.union(I18n.config.interpolation_patterns)) do |match|
          if match == '%%'
            '%'
          else
            key = ($1 || $2 || match.tr("%{}", "")).to_sym
            value = if res.respond_to?(key)
                      res.send(key)
                    else
                      raise ActionController::RoutingError, "You've defined #{key} in the frontend routes, which the #{res.class} class doesn't respond to"
                    end
            $3 ? sprintf("%#{$3}", value) : value
          end
        end
        "https://#{res.tenant.custom_domain}/#{interpolated_route}"
      end
    end
  end


  
  root to: "admin/pages#index"

  resources :webhooks, only: [] do
    collection do
      post 'rebuild'
      post 'netlify_build_status', defaults: {format: :json}

    end
  end

  resources :tenants, only: [] do
    member do
      get 'stylesheet', defaults: {format: :scss}
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord
  include TenantScope
  include SetSanitisedContent
  include SetExcerpt
  include AASM
  include Permalinkable

  extend FriendlyId
  friendly_id :name, use: :scoped, scope: :tenant
  
  belongs_to :user, optional: true
  belongs_to :image, class_name: "Attachments::Image", dependent: :destroy, optional: true
  
  has_many :record_terms, dependent: :destroy
  has_many :taxonomy_terms, through: :record_terms

  has_many :record_attachments_files
  has_many :record_attachments_images
  has_many :record_attachments_video_embeds
  has_many :attached_files, through: :record_attachments_files, source: :attachments_file, dependent: :destroy
  has_many :attached_images, through: :record_attachments_images, source: :attachments_image, dependent: :destroy
  has_many :attached_video_embeds, through: :record_attachments_video_embeds, source: :attachments_video_embed, dependent: :destroy

  # non-core associations
  has_many :collection_records, class_name: "Humap::Collections::CollectionRecord"
  has_many :collections, through: :collection_records, class_name: "Humap::Collections::Collection"

  has_many :trail_records, class_name: "Humap::Trails::TrailRecord"
  has_many :trails, through: :trail_records, class_name: "Humap::Trails::Trail"

  has_many :record_audio_files, class_name: 'Humap::StreamingMedia::RecordAudioFile'
  has_many :audio_files, through: :record_audio_files, class_name: "Humap::StreamingMedia::AudioFile"

  has_rich_text :content

  attr_accessor :active_admin_state_event, :longitude, :latitude

  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :latitude, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :name, presence: true
  validate :date_to_is_after_date_from
  validates :excerpt, length: { maximum: 200 }

  accepts_nested_attributes_for :image, allow_destroy: true
  accepts_nested_attributes_for :attached_images, allow_destroy: true
  accepts_nested_attributes_for :attached_files, allow_destroy: true
  accepts_nested_attributes_for :attached_video_embeds, allow_destroy: true

  before_validation do
    if image.present?
      attached_images << image unless attached_images.include?(image)
    end

    if hero_attachment.present?
      self.hero_attachment_type = hero_attachment.class.to_s.demodulize.underscore
      self.hero_attachment_id = hero_attachment&.id
    end

    if hero_attachment.is_a?(Attachments::VideoEmbed) && !image.present?
      VideoImageDownloaderJob.perform_later(self.id)
    end
    
  end

  after_commit do
    UpdateCollectionFieldsJob.perform_later
  end

  def date_to_is_after_date_from
    return if date_from.blank? || date_to.blank?
  
    if date_to < date_from
      errors.add(:date_to, "can't be before 'date from'") 
    end 
  end

  aasm no_direct_assignment: true, column: :state do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft,
                  to: :published,
                  after: -> {
                    update_attribute(:published_at, published_at ||= DateTime.now)
                  }
    end

    event :unpublish do
      transitions from: :published,
                  to: :draft
    end
  end

  def self.to_geojson
    raise ArgumentError, "You need to set a current tenant" unless Tenant.current.present?
    result = ActiveRecord::Base.connection.execute <<~SQL
      select
          row_to_json(json) as geojson
          FROM ( 
            SELECT 'FeatureCollection' As type, array_to_json(array_agg(f)) As features
              FROM (
                SELECT 'Feature' As type
                , ST_AsGeoJSON(records.lonlat)::json As geometry
                , row_to_json(
                    (
                      SELECT fields FROM (
                        SELECT id, name, state, created_at
                      ) AS fields ) 
                ) AS properties
                FROM records
                WHERE records.tenant_id = #{Tenant.current.id} 
              ) 
            AS f 
          )
          AS json
    SQL
    result.to_json
  end

  def set_lonlat(lon, lat)
    self.lonlat = "POINT(#{lon} #{lat})"
  end

  def longitude
    lonlat&.x
  end

  def latitude
    lonlat&.y
  end

  # This is where we determine what kind of attachment is the 'hero' one, displayed at the top of the record tray on the frontend.
  def hero_attachment
    if attached_video_embeds.any?
      attached_video_embeds.first
    elsif image.present?
      image
    end
  end
end

app/views/admin/records/_form.html.erb
<%= semantic_form_for [:admin, @record], builder: ActiveAdmin::FormBuilder do |f| %>
  <%= f.semantic_errors %>
  <div class="tabs">
      <ul class="nav nav-tabs" role="tablist">
        <li><a href="#basic-content">Basic Content</a></li>
        <li><a href="#media">Media</a></li>
        <li><a href="#location">Location</a></li>
        <li><a href="#categories">Categories</a></li>
        <li><a href="#sharing">Sharing</a></li>
      </ul>
      <div class="tab-content">
          <%= f.inputs do %>
            <div id="basic-content">
                <h3 class="m-fieldset-subheader">Details</h3>
                <%= f.input :name, label: "Title" %>
                <%= f.input :date_from, as: :date_picker, label: "Date from" %>
                <%= f.input :date_to, as: :date_picker, label: "Date to" %>

                <%= render "admin/shared/toggle_published", resource: f.object %>

                <h3 class="m-fieldset-subheader">Main Image</h3>
                <%= f.fields_for :image, allow_destroy: true do |record_image| %>
                  <%= record_image.input :file, as: :file, hint: record_image.object.file.attached? ? ix_image_tag(record_image.object.file.key, url_params: {w: 100, h: 100}) : "" %>
                  <%= record_image.input :name %>
                  <%= record_image.input :credit %>
                <% end %>

                <h3 class="m-fieldset-subheader">Content</h3>
                <div class="m-wysiwyg-container<%= " error" if f.object.errors[:content].any? %>">
                  <%= f.rich_text_area :content %>
                  <% if f.object.errors[:content].any? %>
                    <p class="inline-errors"><%= f.object.errors[:content].first %></p>
                  <% end %>
                </div>
                <%= f.input :excerpt, input_html: { rows: 5 } %>
            </div>

            <div id="media">
              <h3 class="m-fieldset-subheader">Image Gallery</h3>
              <% f.has_many :attached_images, heading: false, allow_destroy: ->(record_image) { record_image.id != f.object.image.try(&:id)} do |record_image| %>
                <% record_image.inputs do %>
                  <% record_image.input :file, as: :file, hint: record_image&.object&.file.attached? ? ix_image_tag(record_image.object.file.key, url_params: {w: 100, h: 100}) : "" %>
                  <% record_image.input :name %>
                  <% record_image.input :credit %>
                <% end %>
              <% end %>

              <h3 class="m-fieldset-subheader">Files</h3>
              <% f.has_many :attached_files, heading: false, allow_destroy: true do |record_file| %>
                <% record_file.inputs do %>
                  <% record_file.input :file, as: :file, hint: record_file&.object&.file.attached? ? record_file.object.file.filename.to_s : "" %>
                  <% record_file.input :name %>
                  <% record_file.input :credit %>
                <% end %>
              <% end %>

              <h3 class="m-fieldset-subheader">Videos</h3>
              <% f.has_many :attached_video_embeds, heading: false, allow_destroy: true do |record_video| %>
                    <% embed_html = record_video.object.metadata.try(:[],'html') %>
                    <% if embed_html.present? %>
                        <div class="embed">
                            <%= embed_html.html_safe %>
                        </div>
                    <% end %>

                <% record_video.inputs do %>
                  <% record_video.input :name %>
                  <% record_video.input :url %>
                <% end %>
              <% end %>
            </div>

            <div id="location">
              <div id="record-map" class="m-record-map-picker"></div>
              <% f.input :latitude, input_html: { id: "latitude", value: f.object.latitude } %>
              <% f.input :longitude, input_html: { id: "longitude", value: f.object.longitude } %>
            </div>

            <div id="categories">
              <%= f.inputs do %>
                <div class="category-container">
                  <% Taxonomy.all.order(:name).in_groups(3).each do |taxonomies| %>
                      <div class="col">
                          <% taxonomies.each do |taxonomy| %>
                              <% next if taxonomy.nil? %>
                              <div class="terms">
                                <h3><%= taxonomy.name %></h3>
                                <% taxonomy.taxonomy_terms.roots.order(:name).each do |term| %>
                                  <input type="checkbox"
                                        id=<%= "record_taxonomy_term_ids_#{term.id}" %>
                                        <%= "class=has-subterms" if taxonomy.display_as == "nested" && term.has_children? %>
                                        name="record[taxonomy_term_ids][]" value=<%= term.id %>
                                        <%= "checked" if f.object.taxonomy_terms.include?(term)%>>
                                  <label for=<%= "record_taxonomy_term_ids_#{term.id}" %>><%= term.name %></label><br>
                                    <% if term.has_children? && taxonomy.display_as == "nested" %>
                                      <div class="subterms" id=<%= "record_taxonomy_term_ids_#{term.id}" %>>
                                        <% term.children.order(:name).each do |subterm| %>
                                          <input type="checkbox"
                                                id=<%= "record_taxonomy_term_ids_#{subterm.id}" %>
                                                name="record[taxonomy_term_ids][]"
                                                value=<%= subterm.id %>
                                                <%= "checked" if f.object.taxonomy_terms.include?(subterm) && taxonomy.display_as == "nested" %>>
                                          <label for=<%= "record_taxonomy_term_ids_#{subterm.id}" %>><%= subterm.name %></label><br>
                                        <% end %>
                                      </div>
                                    <% end %>
                                <% end %>
                              </div>
                          <% end %>
                      </div>
                  <% end %>
                </div>
              <% end %>
            </div>
            <%= render "admin/shared/sharing", resource: f.object %>

          <% end %>
      </div>
  <%= f.actions %>
  </div>
<% end %>